config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => 'registrations'}
  root 'home#index'

  resources :users

  resources :transfers, only: [:index, :create, :destroy]
  resources :balances, only: [:new, :index, :create]
  resources :balance_forecasts, only: [:show]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :transfers

  has_many :balances

  validates :name, presence: true
  after_create :initialize_balance

  def initialize_balance
    Balance.create(:value => 0.0, :on => Time.zone.now, :user => self)
  end

  def transfer_calculator
    @transfer_calculator ||= Transfer::Calculator.new self
  end

  def balance_data
    [balance_log, balance_forecast]
  end

  def balance_log
    bals = balances.order :on
    return [] unless bals.any?
    from = bals.first.on
    to = bals.last.on
    Balance::Calculator.new(balances).balance_log(from, to).sort_by(&:on)
  end

  def balance_forecast
    trans = transfers.order :on
    return [] unless trans.any?
    to = trans.last.on.next_year.to_date
    Balance::Forecaster.new(self).forecast_balance(to).sort_by(&:on)
  end

  def balance
    balances.order(:on).last
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @balance = current_user.balance
    @transfer = Transfer.new

    respond_to do |format|
      format.html { render :show }
      format.json { render json: current_user.balance_data }
      format.csv do
        @balance_log = current_user.balance_log
        @balance_forecast = current_user.balance_forecast
        response.headers['Content-Disposition'] = "attachment; filename=balance_data.csv"
      end
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if current_user.update(user_params)
        format.html { redirect_to current_user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: current_user }
      else
        format.html { render :edit }
        format.json { render json: current_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    current_user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation, :email, :email_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_finance_table.html.erb
<table class="user-finances">
  <thead>
  <th>Date</th>
  <th>Change</th>
  <th>Monthly Change</th>
  <th>Balance</th>
  </thead>
  <tbody id="user-finances-body">
    <% balance_data.each_with_index do |balance, index| %>
      <tr>
        <td><%= balance[:date] %></td>
        <td>£<%= index > 0 ? balance[:value] - balance_data[index - 1][:value]  : 0.0 %></td>
        <td></td>
        <td>£<%= balance[:value] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_finance_table_row.html.erb
<tr>
  <td class="<%= tense + "-date"%>"><%= frow.on %></td>
  <td class="<%= frow.diff > 0 ? (tense + "-pos") : frow.diff < 0 ? (tense + "-neg") : (tense + "-neut") %>"><%= number_to_currency(frow.diff, precision: 2, unit: '£') %></td>
  <td class="<%= frow.running_monthly_diff.nil? ? "" : frow.running_monthly_diff > 0 ? (tense + "-pos") : frow.running_monthly_diff < 0 ? (tense + "-neg") : (tense + "-neut") %>"><%= number_to_currency(frow.running_monthly_diff, precision: 2, unit: '£') %></td>
  <td class="<%= frow.balance > 0 ? (tense + "-pos") : frow.balance < 0 ? (tense + "-neg") : (tense + "-neut") %>"><%= number_to_currency(frow.balance, precision: 2, unit: '£') %></td>
</tr>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :confirm_email %>
    <%= f.email_field :email_confirmation %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :confirm_password %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_nav_bar.html.erb
<nav id="main-nav" class="navbar navbar-default" role="navigation" style="border-radius: 0;">
  <div id="balance-update-container"class="container-fluid">
    <div class="navbar-header">
      <%= link_to current_user.name, current_user, :class => "navbar-brand jura-font" %>
    </div>
    <div class="collapse navbar-collapse">
      <div class="navbar-form navbar-left">
        <%= form_for(balance,
            :remote => true,
            :method => :post,
            :url => new_balance_path) do |f| %>
          <div class="input-group">
            <span class="input-group-addon">£</span>
            <%= f.number_field :value, placeholder: number_with_precision(balance.value, precision: 2), :class => "form-control", :value => "" %>
            <span class="input-group-btn">
              <%= f.button(type: 'submit', class: "btn btn-default") do %>
                Update Balance
              <% end %>
            </span>
          </div>
        <% end %>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Settings <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/users/balance_data.csv.erb
<% require("csv") %>
<%= CSV.generate_line ["Date", "Balance"] %>
<% @user.finance_log.each_with_index do |balance, index| %>
  <% row = [balance.on, balance.value] %>
  <% row << "Balance Log" if index == 0 %>
  <%= CSV.generate_line(row).strip %>
<% end %>
<% @user.finance_forecast.each_with_index do |forecast, index| %>
  <% row = [forecast.date, forecast.balance] %>
  <% row << "Balance Forecast" if index == 0 %>
  <%= CSV.generate_line(row).strip %>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <th>Name</th>
  <th>Balance</th>
  <tbody>
<% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.balance.value %></td>
    </tr>
<% end %>
  </tbody>
<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<%= render 'balances/new', :balance => @balance %>

<p id="notice"><%= notice %></p>

<div class="container">
  <div class="user-transfers col-md-3">
    <h2>Transfers</h2>

    <div class="user-transfers-new">
      <%= render 'transfers/new_transfer_toggle', transfer: @transfer %>
      <%= render 'transfers/new_transfer_form', transfer: @transfer %>
    </div>
    <%= render "transfers/transfers_list", user: current_user %>
  </div>
  <div class="col-md-9">
    <div>
      <%= link_to "Download csv", balances_path(:format => :csv) %>
    </div>
    <canvas id="balance-data">
    </canvas>
    <div id="selected-balance-info" style="float:left;">
    </div>
    <div id="chart_div"></div>
    <%= render "balance_forecasts/blank_slate" %>
  </div>
</div>
<div class="user-data"
  data-balances-url="<%= balances_path(format: :json) %>"
  data-balance-forecast-url="<%= balance_forecast_path %>"
  data-transfers-url="<%= transfers_path %>"
</div>


<!--Load the AJAX API-->
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>